// GENERATED by scripts/export_openapi.py from contract/openapi.json - DO NOT EDIT.
// Change the Pydantic models in backend/app/contract/ (integrate step only), then re-run.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/contract/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contract Events
         * @description Exists so the Event union appears in the API description (for generated types).
         */
        get: operations["contract_events_api_contract_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Replay Meeting */
        post: operations["create_replay_meeting_api_dev_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meetings */
        get: operations["list_meetings_api_meetings_get"];
        put?: never;
        /** Create Meeting */
        post: operations["create_meeting_api_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meeting */
        get: operations["get_meeting_api_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Meeting */
        post: operations["end_meeting_api_meetings__meeting_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_meetings__meeting_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/follow-ups/{follow_up_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Follow Up */
        patch: operations["patch_follow_up_api_meetings__meeting_id__follow_ups__follow_up_id__patch"];
        trace?: never;
    };
    "/api/meetings/{meeting_id}/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mute */
        post: operations["mute_api_meetings__meeting_id__mute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_meetings__meeting_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/wake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wake */
        post: operations["wake_api_meetings__meeting_id__wake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/recall/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall Webhook */
        post: operations["recall_webhook_webhooks_recall__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Alert Id */
            alert_id: string;
            /**
             * Canned
             * @default false
             */
            canned: boolean;
            /** Claim */
            claim: string;
            /** Confidence */
            confidence: number;
            /** Delivered To Chat */
            delivered_to_chat: boolean;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Finding */
            finding: string;
            /** Gate Reason */
            gate_reason?: string | null;
            /** Gated */
            gated: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "contradiction" | "disagreement" | "uncertainty";
            /** Models Used */
            models_used: string[];
            /** Reasoning */
            reasoning: string;
            /** Said By */
            said_by: string[];
            /** Segment Ids */
            segment_ids: string[];
            /** Topic */
            topic: string;
        };
        /** AlertEvent */
        AlertEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["Alert"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "alert";
        };
        /** Body_upload_document_api_documents_post */
        Body_upload_document_api_documents_post: {
            /** File */
            file: string;
        };
        /** BotStatus */
        BotStatus: {
            /** Detail */
            detail?: string | null;
            /** Recall Bot Id */
            recall_bot_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "joining" | "waiting_room" | "in_call" | "left" | "failed";
        };
        /** BotStatusEvent */
        BotStatusEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["BotStatus"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bot.status";
        };
        /** ChatPost */
        ChatPost: {
            /** Chat Id */
            chat_id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "alert" | "answer" | "consent" | "system";
            /** Ref Id */
            ref_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "sent" | "suppressed_muted" | "failed";
            /** Text */
            text: string;
        };
        /** ChatPostEvent */
        ChatPostEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["ChatPost"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chat.post";
        };
        /** CreateMeetingRequest */
        CreateMeetingRequest: {
            /** Meeting Url */
            meeting_url: string;
            /** Title */
            title?: string | null;
        };
        /** DocumentInfo */
        DocumentInfo: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Chunks */
            chunks: number;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Evidence */
        Evidence: {
            /** Document */
            document: string;
            /** Locator */
            locator?: string | null;
            /** Passage */
            passage: string;
        };
        /** FollowUp */
        FollowUp: {
            /** Follow Up Id */
            follow_up_id: string;
            /** Owner */
            owner?: string | null;
            /** Source Alert Id */
            source_alert_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "outstanding" | "resolved";
            /** Text */
            text: string;
        };
        /** FollowUpEvent */
        FollowUpEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["FollowUp"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "follow_up";
        };
        /** FollowUpPatch */
        FollowUpPatch: {
            /**
             * Status
             * @enum {string}
             */
            status: "outstanding" | "resolved";
        };
        /** GateSettings */
        GateSettings: {
            /**
             * Cheap Threshold
             * @default 0.5
             */
            cheap_threshold: number;
            /**
             * Cooldown Seconds
             * @default 90
             */
            cooldown_seconds: number;
            /**
             * Max Alerts Per Meeting
             * @default 8
             */
            max_alerts_per_meeting: number;
            /**
             * Min Confidence
             * @default 0.75
             */
            min_confidence: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Dev Mode */
            dev_mode: boolean;
            /** Offline */
            offline: boolean;
            /** Ok */
            ok: boolean;
            /** Placeholders */
            placeholders: string[];
        };
        /** MeetingEnded */
        MeetingEnded: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "bot_left" | "call_ended" | "dashboard" | "replay_finished";
        };
        /** MeetingEndedEvent */
        MeetingEndedEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["MeetingEnded"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "meeting.ended";
        };
        /**
         * MeetingListItem
         * @description Field order is the sessions-list display order: follow-ups before alerts.
         */
        MeetingListItem: {
            /** Alert Count */
            alert_count: number;
            /** Follow Ups Outstanding */
            follow_ups_outstanding: number;
            /** Follow Ups Resolved */
            follow_ups_resolved: number;
            /** Meeting Id */
            meeting_id: string;
            /** Participants */
            participants: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Title */
            title: string;
        };
        /** MeetingRecord */
        MeetingRecord: {
            /**
             * Alerts
             * @default []
             */
            alerts: components["schemas"]["Alert"][];
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["SpokenAnswer"][];
            /** Bot Status */
            bot_status?: ("joining" | "waiting_room" | "in_call" | "left" | "failed") | null;
            /**
             * Chat Posts
             * @default []
             */
            chat_posts: components["schemas"]["ChatPost"][];
            /** Ended At */
            ended_at?: string | null;
            /**
             * Events Last Seq
             * @default 0
             */
            events_last_seq: number;
            /**
             * Follow Ups
             * @default []
             */
            follow_ups: components["schemas"]["FollowUp"][];
            /** Meeting Id */
            meeting_id: string;
            /** Meeting Url */
            meeting_url?: string | null;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["Participant"][];
            /** Recall Bot Id */
            recall_bot_id?: string | null;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["TranscriptSegment"][];
            /**
             * Source
             * @enum {string}
             */
            source: "recall" | "replay";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            summary?: components["schemas"]["MeetingSummary"] | null;
            /** Title */
            title: string;
        };
        /** MeetingSummary */
        MeetingSummary: {
            /** Alert Count */
            alert_count: number;
            /**
             * Canned
             * @default false
             */
            canned: boolean;
            /** Follow Up Count */
            follow_up_count: number;
            /** Key Topics */
            key_topics: string[];
            /** Takeaways */
            takeaways: string[];
        };
        /** MeetingSummaryEvent */
        MeetingSummaryEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["MeetingSummary"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "meeting.summary";
        };
        /** ModelSettings */
        ModelSettings: {
            /**
             * Answer
             * @default claude-haiku-4-5-20251001
             */
            answer: string;
            /**
             * Cheap Check
             * @default gemini-3.5-flash-lite
             */
            cheap_check: string;
            /**
             * Judge
             * @default claude-haiku-4-5-20251001
             */
            judge: string;
            /**
             * Summary
             * @default claude-haiku-4-5-20251001
             */
            summary: string;
        };
        /** Mute */
        Mute: {
            /**
             * By
             * @default dashboard
             * @constant
             */
            by: "dashboard";
            /** Muted */
            muted: boolean;
        };
        /** MuteEvent */
        MuteEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["Mute"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mute";
        };
        /** MuteRequest */
        MuteRequest: {
            /** Muted */
            muted: boolean;
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** Participant */
        Participant: {
            /** Display Name */
            display_name: string;
            /** Recall Name */
            recall_name?: string | null;
            /** Role */
            role?: string | null;
            /** Speaker Id */
            speaker_id: string;
        };
        /** ReplayMeetingRequest */
        ReplayMeetingRequest: {
            /**
             * Title
             * @default Fake meeting (replay)
             */
            title: string;
        };
        /** Settings */
        Settings: {
            /**
             * Answer Max Words
             * @default 60
             */
            answer_max_words: number;
            /**
             * Bot Name
             * @default Meet AGI
             */
            bot_name: string;
            /**
             * Consent Text
             * @default Meet AGI is listening to help with facts from our documents. It may post short notes here. Say "Hey AGI" to ask it something, or "AGI, stop talking" to stop it.
             */
            consent_text: string;
            /**
             * Fillers
             * @default [
             *       "Sure, let me look that up.",
             *       "One moment, checking the documents.",
             *       "Good question, give me a second."
             *     ]
             */
            fillers: string[];
            /**
             * @default {
             *       "cheap_threshold": 0.5,
             *       "cooldown_seconds": 90,
             *       "max_alerts_per_meeting": 8,
             *       "min_confidence": 0.75
             *     }
             */
            gate: components["schemas"]["GateSettings"];
            /**
             * @default {
             *       "answer": "claude-haiku-4-5-20251001",
             *       "cheap_check": "gemini-3.5-flash-lite",
             *       "judge": "claude-haiku-4-5-20251001",
             *       "summary": "claude-haiku-4-5-20251001"
             *     }
             */
            models: components["schemas"]["ModelSettings"];
            /**
             * Speakers
             * @default []
             */
            speakers: components["schemas"]["SpeakerMapping"][];
            /**
             * Stop Variants
             * @default [
             *       "agi stop talking",
             *       "a g i stop talking",
             *       "aji stop talking",
             *       "agi stop",
             *       "stop talking agi"
             *     ]
             */
            stop_variants: string[];
            /**
             * @default {
             *       "model": "inworld-tts-2",
             *       "provider": "inworld",
             *       "voice_id": "Grant"
             *     }
             */
            voice: components["schemas"]["VoiceSettings"];
            /**
             * @default {
             *       "max_word_position": 3,
             *       "question_wait_seconds": 8,
             *       "variants": [
             *         "hey agi",
             *         "hey a g i",
             *         "hey aji",
             *         "hey age i",
             *         "hey a gi",
             *         "hey ag i",
             *         "hi agi",
             *         "hey agee"
             *       ]
             *     }
             */
            wake: components["schemas"]["WakeSettings"];
        };
        /** SpeakerMapping */
        SpeakerMapping: {
            /** Display Name */
            display_name: string;
            /** Match Name */
            match_name: string;
            /** Role */
            role?: string | null;
        };
        /** SpokenAnswer */
        SpokenAnswer: {
            /** Answer Id */
            answer_id: string;
            /** Asked By */
            asked_by?: string | null;
            /**
             * Canned
             * @default false
             */
            canned: boolean;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Question */
            question: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "playing" | "played" | "stopped" | "muted" | "failed";
            /** Text */
            text: string;
        };
        /** SpokenAnswerEvent */
        SpokenAnswerEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["SpokenAnswer"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "spoken.answer";
        };
        /** Stop */
        Stop: {
            /** Segment Id */
            segment_id?: string | null;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "phrase" | "button";
        };
        /** StopEvent */
        StopEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["Stop"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stop";
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Segment Id */
            segment_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "recall" | "replay" | "manual";
            /** Speaker Id */
            speaker_id: string;
            /** Speaker Name */
            speaker_name: string;
            /** T End */
            t_end: number;
            /** T Start */
            t_start: number;
            /** Text */
            text: string;
        };
        /** TranscriptSegmentEvent */
        TranscriptSegmentEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["TranscriptSegment"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transcript.segment";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoiceSettings */
        VoiceSettings: {
            /**
             * Model
             * @default inworld-tts-2
             */
            model: string;
            /**
             * Provider
             * @default inworld
             * @constant
             */
            provider: "inworld";
            /**
             * Voice Id
             * @default Grant
             */
            voice_id: string;
        };
        /** Wake */
        Wake: {
            /** Matched Variant */
            matched_variant?: string | null;
            /** Question */
            question?: string | null;
            /** Segment Id */
            segment_id?: string | null;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "phrase" | "button";
        };
        /** WakeEvent */
        WakeEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: string;
            /** Meeting Id */
            meeting_id: string;
            payload: components["schemas"]["Wake"];
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "wake";
        };
        /** WakeRequest */
        WakeRequest: {
            /** Question */
            question?: string | null;
        };
        /** WakeSettings */
        WakeSettings: {
            /**
             * Max Word Position
             * @default 3
             */
            max_word_position: number;
            /**
             * Question Wait Seconds
             * @default 8
             */
            question_wait_seconds: number;
            /**
             * Variants
             * @default [
             *       "hey agi",
             *       "hey a g i",
             *       "hey aji",
             *       "hey age i",
             *       "hey a gi",
             *       "hey ag i",
             *       "hi agi",
             *       "hey agee"
             *     ]
             */
            variants: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contract_events_api_contract_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotStatusEvent"] | components["schemas"]["TranscriptSegmentEvent"] | components["schemas"]["WakeEvent"] | components["schemas"]["StopEvent"] | components["schemas"]["MuteEvent"] | components["schemas"]["AlertEvent"] | components["schemas"]["SpokenAnswerEvent"] | components["schemas"]["ChatPostEvent"] | components["schemas"]["FollowUpEvent"] | components["schemas"]["MeetingSummaryEvent"] | components["schemas"]["MeetingEndedEvent"];
                };
            };
        };
    };
    create_replay_meeting_api_dev_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayMeetingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"][];
                };
            };
        };
    };
    upload_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_meetings_api_meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListItem"][];
                };
            };
        };
    };
    create_meeting_api_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_meeting_api_meetings__meeting_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_meetings__meeting_id__events_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events; each `data:` line is one Event (schema: GET /api/contract/events). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_follow_up_api_meetings__meeting_id__follow_ups__follow_up_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
                follow_up_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUp"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mute_api_meetings__meeting_id__mute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotStatusEvent"] | components["schemas"]["TranscriptSegmentEvent"] | components["schemas"]["WakeEvent"] | components["schemas"]["StopEvent"] | components["schemas"]["MuteEvent"] | components["schemas"]["AlertEvent"] | components["schemas"]["SpokenAnswerEvent"] | components["schemas"]["ChatPostEvent"] | components["schemas"]["FollowUpEvent"] | components["schemas"]["MeetingSummaryEvent"] | components["schemas"]["MeetingEndedEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_meetings__meeting_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotStatusEvent"] | components["schemas"]["TranscriptSegmentEvent"] | components["schemas"]["WakeEvent"] | components["schemas"]["StopEvent"] | components["schemas"]["MuteEvent"] | components["schemas"]["AlertEvent"] | components["schemas"]["SpokenAnswerEvent"] | components["schemas"]["ChatPostEvent"] | components["schemas"]["FollowUpEvent"] | components["schemas"]["MeetingSummaryEvent"] | components["schemas"]["MeetingEndedEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wake_api_meetings__meeting_id__wake_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotStatusEvent"] | components["schemas"]["TranscriptSegmentEvent"] | components["schemas"]["WakeEvent"] | components["schemas"]["StopEvent"] | components["schemas"]["MuteEvent"] | components["schemas"]["AlertEvent"] | components["schemas"]["SpokenAnswerEvent"] | components["schemas"]["ChatPostEvent"] | components["schemas"]["FollowUpEvent"] | components["schemas"]["MeetingSummaryEvent"] | components["schemas"]["MeetingEndedEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recall_webhook_webhooks_recall__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
