"""
WHY THIS EXISTS
Generates the two files every other part of the system reads the contract
from - never edit them by hand:
  contract/openapi.json                  the API description, from the backend code
  frontend/src/contract/schema.d.ts      TypeScript types, from openapi.json
With --check it regenerates into memory and fails if the committed files are
out of date (used by scripts/verify.py).

FAILURE IT PREVENTS
The dashboard compiling against yesterday's data shapes (CLAUDE.md rule 3).

DEPENDENCY (CLAUDE.md rule 4): openapi-typescript 7.13.0 via npx (needs
Node.js, already installed). Free. Without it the dashboard types would be
hand-written. Pinned so regenerating never changes output by surprise.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bootstrap import ROOT, ensure_venv  # noqa: E402

ensure_venv()
sys.path.insert(0, str(ROOT))

OPENAPI = ROOT / "contract" / "openapi.json"
TS_OUT = ROOT / "frontend" / "src" / "contract" / "schema.d.ts"
OPENAPI_TS = "openapi-typescript@7.13.0"
TS_HEADER = ("// GENERATED by scripts/export_openapi.py from contract/openapi.json - DO NOT EDIT.\n"
             "// Change the Pydantic models in backend/app/contract/ (integrate step only), then re-run.\n")


def build_openapi() -> str:
    os.environ.setdefault("MEETAGI_DATA_DIR", tempfile.mkdtemp())  # don't touch real data
    from backend.app.main import create_app
    return json.dumps(create_app().openapi(), indent=2, sort_keys=True) + "\n"


def build_ts(openapi_text: str) -> str:
    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        sys.exit("Node.js (npx) not found - install Node.js LTS to generate TypeScript types.")
    with tempfile.TemporaryDirectory() as tmp:
        src, out = Path(tmp) / "openapi.json", Path(tmp) / "schema.d.ts"
        src.write_text(openapi_text, encoding="utf-8")
        subprocess.run([npx, "--yes", OPENAPI_TS, str(src), "-o", str(out)], check=True,
                       capture_output=True, text=True)
        return TS_HEADER + out.read_text(encoding="utf-8").replace("\r\n", "\n")


def main() -> int:
    check = "--check" in sys.argv
    openapi_text = build_openapi()
    ts_text = build_ts(openapi_text)
    if check:
        problems = []
        if not OPENAPI.exists() or OPENAPI.read_text(encoding="utf-8").replace("\r\n", "\n") != openapi_text:
            problems.append("contract/openapi.json is out of date")
        if not TS_OUT.exists() or TS_OUT.read_text(encoding="utf-8").replace("\r\n", "\n") != ts_text:
            problems.append("frontend/src/contract/schema.d.ts is out of date")
        if problems:
            print("CONTRACT DRIFT: " + "; ".join(problems) + " - run: python scripts/export_openapi.py")
            return 1
        print("Contract files match the backend models.")
        return 0
    OPENAPI.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI.write_text(openapi_text, encoding="utf-8", newline="\n")
    TS_OUT.write_text(ts_text, encoding="utf-8", newline="\n")
    print(f"Wrote {OPENAPI.relative_to(ROOT)} and {TS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
